### PR TITLE
Vibrancy (fixes #5)

### LINKED ISSUE #5: [Feature-request] Add the transparency bar
Hey!

I really like your repository and I've spread the news on social platforms. But my question is, can you add the transparency slider for the terminal? Like the one that Ubuntu has?

### PR DESCRIPTION
**Pull request by Eugeny**

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
Is Vibrancy working at the moment? If so, could you please add an a screenshot?

**Comment by Eugeny** [comment]
Yes, but not in the released builds yet. Vibrancy is available for macOS and transparency is available for macOS & Windows.

I'm working on getting vibrancy on Windows and transparency on Linux at the moment.


Vibrancy:

screenshot 2018-08-06 at 10 35 19

Transparency:

screenshot 2018-08-06 at 10 35 51

**Comment by DRSDavidSoft** [comment]
Nice. If you could make it look [like this](https://github.com/Microsoft/vscode/issues/32257) on macOS, it'd be awesome!

**Comment by Eugeny** [comment]
It does look this way with an appropriate wallpaper and background tint disabled: 

image

I've left some background tint in, because a lot of bright wallpapers make the terminal text unreadable without it. But it's all configurable with user CSS of course

**Comment by Eugeny** [comment]
With the tint fully disabled: 
image

**Comment by DRSDavidSoft** [comment]
@Eugeny This is amazing! Wish the same effect could be achieved on Windows. Can you take a look at [23phy/electron-acrylic](https://github.com/23phy/electron-acrylic)? here's [a sample](https://github.com/arkenthera/electron-vibrancy/issues/21#issuecomment-388995142).

**Comment by DRSDavidSoft** [comment]
@Eugeny Awesome. Should Windows' "blur-behind" be in a new issue instead of this one?

**Comment by Eugeny** [comment]
image

I'll be pushing windows vibrancy support into master soon

**Comment by DRSDavidSoft** [comment]
@Eugeny This is so cool! ❤️  I wish it could get more blurred, so we could achieve the same effect as running on macOS

**Comment by sylveon** [comment]
My PR to vscode for the effect does have a more intense blur on Windows: https://github.com/Microsoft/vscode/pull/52707

**Comment by Eugeny** [comment]
@sylveon does your solution also work with window snapping? (win key + arrows)?

**Comment by sylveon** [comment]
Yes, you can see me playing with them here https://www.youtube.com/watch?v=K2qw0fKGE60

**Comment by smlombardi** [comment]
I've seen multiple posts on this for months, anyone have any idea if it will ever see the light of day?

**Comment by Eugeny** [comment]
@smlombardi it's long released, were now talking about an alternative implementation by @sylveon

**Comment by smlombardi** [comment]
@Eugeny I can use this in my themes for Insiders now?
Are there docs for us theme authors as to how to integrate transparency in our themes?

**Comment by Eugeny** [comment]
@smlombardi all you need is have a transparent `background-color` on the body. If vibrancy is enabled by the user, it will have the `.vibrant` class.

**Comment by smlombardi** [comment]
So how does one enable vibrancy?

>If vibrancy is enabled by the user

**Comment by Eugeny** [comment]
@sylveon now in master - thank you so much!

**Comment by Eugeny** [comment]
@smlombardi Settings -> Appearance -> Vibrancy 
image

**Comment by sylveon** [comment]
Awesome! A few tips tho:

- As I've noted in the configuration option on vscode, the fluent appearance is really buggy at times ([video](https://youtu.be/gkCgj-Dpy44), I've made the editor background fully transparent to highlight it better) so not sure if you want to ship that as default, an optional setting to enable it or making the vibrancy a dropdown with different appearances is probably better. It's nothing your app can fix, it's something in DWM.
- macOS doesn't needs electron-vibrancy anymore, as electron natively supports it. See the `vibrancy` property of the browser window create options, as well as `window.setVibrancy`
- On Linux, it's also possible to do, if you can afford the loss of hardware accelerated rendering (which a small app like Terminus should be fine with, after all vscode without hardware acceleration works well on my lower end laptop). Note that in this case, you can only enable transparency and it's up to the user's compositor to render the blur effect.

**Pull request merged**
