### PR TITLE
use base16-xresources

### PR DESCRIPTION
**Pull request by tnguyen14**
I realized that the author of this theme maintains an XResources file, so I figured I'd just copy from it directly.

### CODE REVIEW

**Comment by tnguyen14** [comment]
@Eugeny do you know why the appveyor build might have failed?

**Comment by Eugeny** [comment]
Have you tested the changes locally?

**Comment by tnguyen14** [comment]
No I have not, I didn't expect the changes to have any build impact, but I could be wrong as the last time I contributed was months ago. I will try to run the test locally tonight.

**Comment by Eugeny** [comment]
The problem is that the Xresources parser in Terminus can't handle variables. (the failed build isn't related to your pull request)

**Comment by tnguyen14** [comment]
Thanks. Could you point me to where the Xresources parser is in Terminus? I tried to look around briefly, but it wasn't obvious to me.

**Comment by tnguyen14** [comment]
If we can't change the parser, I think I can manually translate it to what the values should be. Upon inspection, it looks like the new one just add colors 17-21, and the old one has `colorBD` defined.

**Comment by Eugeny** [comment]
Link to the parser: https://github.com/Eugeny/terminus/blob/master/terminus-community-color-schemes/src/colorSchemes.ts

**Comment by tnguyen14** [comment]
Thanks for the reference. Do you know how the colors are used? I see that it is only configured to accepts colors from 0 to 15. If I add colors 16-21, will the renderer pick them up?

**Comment by Eugeny** [comment]
I've just updated the parser to include any colors beyond 16. Could you please try it out with your theme?

**Comment by tnguyen14** [comment]
I'm trying to run with the latest master - after `npm run build` and `npm start`, when the app loads, I see the following error on the devtools console

```
ERROR Error: Uncaught (in promise): [object Object]
    at resolvePromise (/Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:770)
    at /Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:696
    at rejected (css-base.js:75)
    at ZoneDelegate.invoke (/Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:391)
    at Object.onInvoke (ng_zone.ts:296)
    at ZoneDelegate.invoke (/Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:390)
    at Zone.run (/Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:141)
    at /Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:818
    at ZoneDelegate.invokeTask (/Users/tnguyen541/github/Eugeny/terminus/app/node_modules/zone.js/dist/zone.js:424)
    at Object.onInvokeTask (ng_zone.ts:288)
```

Upon clicking the `+` button to create a new shell, nothing happens and the same error appears.

I know the error doesn't seem to be very helpful. I was wondering if you see any similar error on your end?

**Comment by tnguyen14** [comment]
I also see the following error in the console, but I'm not sure if it's related

```
> cross-env DEV=1 electron --js-flags='--ignition' app --debug

Host startup: 128ms
2017-11-28 00:27:43.398 Electron Helper[97949:4646066] Couldn't set selectedTextBackgroundColor from default ()
info: v 1.0.0-alpha.1
info: Update available: 1.0.0-alpha.37
```

**Comment by tnguyen14** [comment]
@Eugeny do you know how I could debug this? The stack trace isn't very helpful. I've tried re-running `npm run build` but that doesn't do anything.

**Comment by Eugeny** [comment]
Sorry for the delay. You can enable "stop on exceptions" in the DevTools, that should get you to the point it crashes at.

**Comment by tnguyen14** [comment]
Thanks for the tip!

The `[object Object]` above is as follows:

```js
{
  "time": 1512172203,
  "number": 302,
  "lines": [
    "invalid option: bell-on-alert"
  ],
  "error": true
}
```

It is of type `TMuxBlock`.

**Comment by Eugeny** [comment]
Which tmux version are you running?

**Comment by tnguyen14** [comment]
```sh
:; tmux -V
tmux 2.6
```

**Comment by tnguyen14** [comment]
@Eugeny is there a different tmux version I should try with?

**Comment by tnguyen14** [comment]
@Eugeny Do you have any suggestion here on how I can continue to debug this?

**Comment by Eugeny** [comment]
Please post this tmux error as a separate bug and switch to Screen or disable session persistence.

**Comment by tnguyen14** [comment]
I've updated the script to process `#define` lines as well.

So the theme as it is will work. The only thing the processor doesn't know about is `#ifdef` and `[background_opacity]`. However, it will read `*.background` twice, and so the second value will override the first, so it works.

**Comment by Eugeny** [comment]
Looks good now!

**Comment by tnguyen14** [comment]
Thanks! Please let me know when this is released as a version, I will download it on my Windows machine and test it there.

**Pull request merged**
