### PR TITLE
Create close pane hotkey.

### PR DESCRIPTION
**Pull request by Mezner**
I wanted to have an ability to close panes as easily as creating them, so I created a simple shortcut for it.

### CODE REVIEW

**Comment by Eugeny** [comment]
Thanks a lot!

**Comment by Mezner** [comment]
Thanks for the merge. Is there a way I can self-release a mac dmg so I can run this without engaging another terminal? How often do you cut releases?

**Comment by Eugeny** [comment]
Generally, just every now and then. I've just started the Alpha 74 build, but in the future you can follow the steps here: https://github.com/Eugeny/terminus/blob/master/.travis.yml#L29

**Comment by Eugeny** [comment]
@all-contributors add @mezner for code

**Pull request merged**
