### PR TITLE
Fix: save plugins to path `UserData` for fit portable mode

### PR DESCRIPTION
**Pull request by CyrilTaylor**

### CODE REVIEW

**Comment by Eugeny** [comment]
What is Sentry using `userData` for? If it's just crash info, it's actually better to keep it local to the PC instead of portable data.

**Comment by CyrilTaylor** [comment]
> What is Sentry using `userData` for? If it's just crash info, it's actually better to keep it local to the PC instead of portable data.

terminus-data\sentry\scope_v2.json

**Comment by Eugeny** [comment]
Yeah - it's definitely OK to keep it local. I'll merge your first commit and close this PR

**Comment by CyrilTaylor** [comment]
But I think the user who like portable mode want to keep local pure.

**Comment by Eugeny** [comment]
Good point. Can you move it to its own file then? (portable.ts, to be included before sentry.ts)

**Comment by Eugeny** [comment]
Thanks!

**Pull request merged**
