### PR TITLE
Apple Silicon support

### LINKED ISSUE #3204: Apple Silicon M1 support
Hello,

Will see if I will be able to contribute, but Electron 11 is already available with support of M1. 

Perhaps you could look into this to make a build of the same for Apple Silicon

pinpin

### PR DESCRIPTION
**Pull request by pinpins**
Hello,

This brings a bit awkward Apple Silicon support(arm64), by upgrading some of key dependencies:

1. Node 15
2. Electron 11.1
3. binding.gyp_hack should be part of new NPM @terminus-term, where c++11 compiler hardcode should be removed for mac
4. In order to build locally /scripts/local-release-macos.sh should be used
5. yarn.lock files can be ignored ofc

Cheers, pinpin

Fixes #3204

### CODE REVIEW

**Comment by Eugeny** [comment]
Fantastic work! I'll be adding a few more fixes

**Comment by pinpins** [comment]
Huh, quite some more changes to adapt for electron11 👍 

Indeed, I also have had some issues with electron screen object, and display change events.

**Comment by Eugeny** [comment]
@allcontributors please add @pinpins for code

**Comment by pinpins** [comment]
Please fix Release notes, pinpins is the right reference  👍 
`
Added ARM macOS builds 🍏 (by @pinpins )`

**Comment by Eugeny** [comment]
Done, sorry :D

**Pull request merged**
